spring:
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-xny
      access-key: LTAI4GFG5FSEeZdGqpRUzoHr
      secret-key: IVElmMuzzxLiAyKWarr77nVnxhupv7
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        appcode: 6a70a63e15844e42816c70eaa133296e
        effectiveTime: 10
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-third-party

server:
  port: 40000
