spring:
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-xny
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        effectiveTime: 10
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-third-party

server:
  port: 40000
